DECLARE
v_CODPROF professor.codprof%TYPE;
BEGIN
SELECT PR.CODPROF FROM PROFESSOR PR, PROFTURMA PT
INTO v_CODPROF
WHERE PT.CODPROF = PR.CODPROF
AND PR.CODTIT = '1'
AND PR.CODPROF NOT IN (SELECT PT.CODPROF FROM PROFTURMA PT
      WHERE PT.ANOSEM = '20191');
      IF NOT v_CODPROF%FOUND THEN
		RAISE NO_DATA_FOUND;
        END IF;
EXCEPTION
  when no_data_found then
    raise_application_error(-20201, 'Professor não existe!!!');
  when others then
    dbms_output.put_line('sqlcode: ' || sqlcode);
END;



--alterar
CREATE OR REPLACE PROCEDURE GET_DOCTORS IS
	CODPROF NUMBER(6);
	CURSOR C1 
	IS 
		SELECT DISTINCT PR.CODPROF FROM PROFESSOR PR, PROFTURMA PT
            WHERE PT.CODPROF = PR.CODPROF
            AND PR.CODTIT = '1'
            AND PR.CODPROF NOT IN (SELECT PT.CODPROF FROM PROFTURMA PT
                                    WHERE PT.ANOSEM = '20191');

BEGIN									  
	OPEN C1;
	
	IF C1%NOTFOUND THEN
		RAISE NO_DATA_FOUND;
	END IF;
    
        LOOP
            FETCH C1 INTO CODPROF;
            
            EXIT WHEN C1%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('CODIGO DE PROFESSOR:' || CODPROF);
            
        END LOOP;
		CLOSE C1;
	
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NENHUM DOUTOR FOI ENCONTRADO!');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERRO GENÉRICO!');

END;
