CREATE OR REPLACE TRIGGER TRG_DOCTORS BEFORE
        INSERT ON PROFESSOR
        FOR EACH ROW

DECLARE
    VENCONTRADO NUMBER(1);
    ERRO_DOUTOR EXCEPTION;
BEGIN
   SELECT COUNT(1) INTO VENCONTRADO
    FROM PROFESSOR PROF, TITULACAO TIT
        WHERE PROF.CODTIT = TIT.CODTIT     
        AND PROF.CODTIT = :NEW.CODTIT
        AND   TIT.NOMETIT = 'DOUTOR';
    IF VENCONTRADO = 0 THEN
        RAISE ERRO_DOUTOR;
    END IF;
    EXCEPTION
        WHEN ERRO_DOUTOR THEN
            SYS.DBMS_OUTPUT.PUT_LINE('NÃO FOI POSSÍVEL INSERIR, SOMENTE PROFESSORES COM O TÍTULO DE DOUTOR');
        WHEN OTHERS THEN
            SYS.DBMS_OUTPUT.PUT_LINE('ERRO');
END;